version: '3.7'

services:
  jenkins:
    container_name: neo_jenkins
    hostname: jenkins
    image: 'jenkins/jenkins:lts'
    privileged: true
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:8080/login"]
    volumes:
      - "jenkins_data:/var/jenkins_home"
    networks:
     - local

  nexus:
    container_name: neo_nexus
    hostname: nexus
    image: 'sonatype/nexus3:3.30.1'
    ports:
      - '8081:8081'
    volumes:
      - "./nexus:/nexus-data"
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:8081/"]
    networks:
      - local
    links:
      - jenkins

  gogs:
    container_name: neo_gogs
    image: 'gogs/gogs:0.12.3'
    hostname: gogs
    ports:
      - '10022:22'
      - '3000:3000'
    volumes:
      - 'gogs_data:/data'
    networks:
      - local

  sonarqube:
    hostname: sonarqube
    image: sonarqube
    container_name: sonarqube
    expose:
      - 9000
    ports:
      - 9000:9000
    user: "999"
    depends_on:
      - db
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - "./sonarqube/data:/opt/sonarqube/data"
      - "./sonarqube/extensions:/opt/sonarqube/extensions"
      - "./sonarqube/logs:/opt/sonarqube/logs"
    networks:
      - local

  db:
    hostname: db
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - local

volumes:
  nexus-data: {}
  jenkins_data:
    driver: local
  gogs_data:
    driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:

networks:
  local:
    driver: bridge
