version: '3.7'

services:
  jenkins:
    container_name: neo_jenkins
    hostname: jenkins
    image: 'jenkins/jenkins:lts'
    privileged: true
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:8080/login"]
    volumes:
      - ~/jenkins:/var/jenkins_home
    networks:
     - local

  nexus:
    container_name: neo_nexus
    hostname: nexus
    image: 'sonatype/nexus3:3.30.1'
    ports:
      - '8081:8081'
    volumes:
      - "./nexus:/nexus-data"
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:8081/"]
    networks:
      - local
    links:
      - jenkins

  gogs:
    container_name: neo_gogs
    image: 'gogs/gogs:0.12.3'
    hostname: gogs
    ports:
      - '10022:22'
      - '3000:3000'
    volumes:
      - 'gogs_data:/data'
    networks:
      - local

  postgres:
    hostname: postgres
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - local

  sonarqube:
    hostname: sonarqube
    image: sonarqube
    container_name: sonarqube
    ports:
      - 9000:9000
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: ${DB_USER}
      SONAR_JDBC_PASSWORD: ${DB_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - local

volumes:
  nexus-data: {}
  jenkins_data:
    driver: local
  gogs_data:
    driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data:

networks:
  local:
    driver: bridge